// src/js/constants/action-types.js
export const GET_REPOS = 'GET_REPOS';
export const REPOS_FETCHED_INIT = 'REPOS_FETCHED_INIT';
export const REPOS_FETCHED_SUCCESS = 'REPOS_FETCHED_SUCCESS';
export const REPOS_PAGINATION_FETCHED_SUCCESS =
  'REPOS_PAGINATION_FETCHED_SUCCESS';
export const REPOS_FETCHED_ERROR = 'REPOS_FETCHED_ERROR';

export const USER_REPOS_FETCHED = 'USER_REPOS_FETCHED';
export const USER_GITHUB_REPOS_FETCHED = 'USER_GITHUB_REPOS_FETCHED';
export const USER_GITHUB_REPOS_PUBLISHED = 'USER_GITHUB_REPOS_PUBLISHED';
export const USER_GITHUB_REPOS_REMOVED = 'USER_GITHUB_REPOS_REMOVED';

export const SUBSCRIBE_EMAIL_INIT = 'SUBSCRIBE_EMAIL_INIT';
export const SUBSCRIBE_EMAIL_SUCCESS = 'SUBSCRIBE_EMAIL_SUCCESS';
export const SUBSCRIBE_EMAIL_ERROR = 'SUBSCRIBE_EMAIL_ERROR';

export const SELECTED_LANGUAGE = 'SELECTED_LANGUAGE';
