// src/js/constants/action-types.js
export const GET_REPOS = "GET_REPOS";
export const REPOS_FETCHED = "REPOS_FETCHED";
export const USER_REPOS_FETCHED = "USER_REPOS_FETCHED";
export const USER_GITHUB_REPOS_FETCHED = "USER_GITHUB_REPOS_FETCHED";
export const USER_GITHUB_REPOS_PUBLISHED = "USER_GITHUB_REPOS_PUBLISHED";
export const USER_GITHUB_REPOS_REMOVED = "USER_GITHUB_REPOS_REMOVED";
